version: '3.3'
services:
  books_db:
    image: test_db
    networks:
      - bookstore
    environment:
      MYSQL_ROOT_PASSWORD: asdfgh
    ports:
      - "3306:3306"

networks:
  bookstore:
    external: true
