version: '3.3'
services:
  books_db:
    build: .
    networks:
      - bookstore
    environment:
      MYSQL_ROOT_PASSWORD: ${BOOKS_DB_PASSWORD}
    ports:
      - "${BOOKS_DB_PORT}:${BOOKS_DB_PORT}"

networks:
  bookstore:
    external: true
